### ISSUE TITLE
Show logs of erroneous Test runs to user

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#23]
Currently, when a test fails in whatever fashion (i.e. timeout), the exception in the peass process happens at a later time and for different reasons, thus the Exceptions shown in the jenkins Console are products of the peass process that the user cannot interpret easily.
Additionally the erroneous Tests and their respective logs should be shown or referenced for the jenkins user.

**Comment by DaGeRe** [comment]
This is a good idea, users should have access to the logs (for errorneus runs and also to search look at the behaviour of single VM executions, e.g. if special log outputs may indicate different performance behaviour).
I basically implemented this in https://github.com/DaGeRe/peass-ci/commit/9b304b75fd76939b1038fd314e91cd635e95f063. If you install the newest version and add `displayLogs: true` to your configuration, the logs are added. Since logs may contain much data and Jenkins internally stores this data, this is not activated by default and does not work for past logs. Does this feature work for you this way?

Currently, the links to the logs are only visible through the log overview and RCA logs are not displayable. We should discuss how this should be organized at the next meeting.

**Comment by DaGeRe** [comment]
After the discussion in the meeting, I now also implemented displaying of RTS and RCA logs, it is available since https://github.com/DaGeRe/peass-ci/commit/67cf4d2ed3eb61fee7ca11205e628bbc153355da .
Since this basically work, I close this issue. If logs are missing or there are errors in specific log displaying, feel free to create a new specific issue.
