### ISSUE TITLE
Show more measurement info to user

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#24]
Currently the information on the measured times are presented as a single graph in the jenkins action "Performance Measurement". Whereas the results of the Root Cause Analsysis are shown in greater detail for each node.
Bring the represented information in "Performance Measurement" up to par with those in RCA.

**Comment by Schattensilber** [comment]
One aspect of this is to allow measurement trend visualization for signular VM execution for Regular Performance Measurement (without RCA)

**Comment by DaGeRe** [comment]
Thanks for the idea, I added the following information about measurements in https://github.com/DaGeRe/peass-ci/commit/f040c57d2049792abce36852ececa6a9e9f16e8e:
- Fix link to _outer_ measurement that is also done when RCA is executed (which is `/dashboard?call=overall&ess=-1`) in RCA view
- Add link to _outer_ measurement from RCA to overall graph
- Table for statistical data of uninstrumented measurement (without instrumentation, which is used for RCA)

As far as I see, the values of uninstrumented measurement (which is always __outer__, since no inner measurement is done without instrumentation) differ significantly from the __outer__ measurement in RCA. Therefore, one final step to complete this issue would be to visualize the uninstrumented measurement.

**Comment by DaGeRe** [comment]
Now, measurement values from the uninstrumented runs can also be visualized, therefore this should work from my point of view. Does this also work for you?
