### ISSUE TITLE
Text in Measurement page

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#39]
One headline there is "Messungen", should probably be english ;)

**Comment by DaGeRe** [comment]
I started localizing parts of the plugin. Therefore, if your browser is configured to show german websites, it will show the already localized parts in german. 

The localization files are https://github.com/DaGeRe/peass-ci/blob/develop/src/main/resources/de/dagere/peass/ci/MeasureVersionBuilder/config_de.properties and https://github.com/DaGeRe/peass-ci/blob/develop/src/main/resources/de/dagere/peass/ci/MeasureVersionBuilder/config.properties, since the english file does not contain "Messungen", I assume that this happens because of the german configuration of your browser.

**Comment by Schattensilber** [comment]
Ah, that explains it :)

**Comment by DaGeRe** [comment]
Sorry, you were right, during localization, I entered a wrong english name. This his fixed now: https://github.com/DaGeRe/peass-ci/commit/02dce7380066170dd52f25eb48785ab09bcd3783 thanks for the hint!
