### ISSUE TITLE
Standard Deviation in Measurement and Inspect Measurement page differ

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#40]
The deviation values are currently hard to understand.
It seems to me it would be useful to present them in the same unit as the measurement time and difference to be better comparable to those numbers.

**Comment by DaGeRe** [comment]
Thanks for the hint, this had two reasons:
- The measurements on Inspect Measurement page are without repetitions, the measurements on Measurement page are with warmup
- The measurements on Inspect Measurement page are without warmup removed (since you should be able to choose warmup individually), but the measurements on the Measurement page are with removed warmup to get a quick overview

I changed it so non-warmed up values are also display on measurement page (https://github.com/DaGeRe/peass-ci/commit/93432cf29bec52dedd8b9272fb855a16cd62e74b). Now, the values should be less confusing.
