### ISSUE TITLE
Use 'Includes' for regression test selection

### ISSUE THREAD

**Issue by Schattensilber** [DaGeRe/peass-ci#5]
The Includes option allows to specify only a subset of tests to be measured by peass. At the moment the regression test selection phase seems to still instrument all tests regardless of Includes.

**Comment by DaGeRe** [comment]
Thanks for the issue. I will fix this in the next days.

**Comment by DaGeRe** [comment]
It is now checked whether a test is included or not, therefore, since https://github.com/DaGeRe/peass/commit/cbff8f14fc3140cd2f9bc446749d32c9cbe58114, this should also work for the regression test selection (RTS). It is implemented by checking for the executions whether a test is included. 

Could you check whether this works for you? For testing, you should clean ~/.peass/ before execution and use a fresh build of peass and peass-ci.

One thing that will *not* work is first including only `TestA`, executing the RTS and then including `TestB` - `TestB` will not be selected afterwards. After the initial identification of tests and dependencies in the RTS, updates will only be performed on known tests; therefore, extending the definition of includes will currently not work (but shortening the definition will work). The easiest implementation for this would be to save the includes of the last execution and re-execute the initial identification of tests, if the definition of includes is extended; I'll try to implement this in the next days.

**Comment by Schattensilber** [comment]
Currently not working at all. Console readout is very different depending on whether includes is set or not. Will give you details through different channel.

**Comment by Schattensilber** [comment]
Seems to work now, thanks!
